# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rake secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

development:
  secret_key_base: 4d38b7e1a9fdcb7d694b388febdc8de43b0f72d0232f9da059a6f353e3c4032e81a22d195f48b7a0671496b39a22f8289f0db0a4964ea907141ac9eacfdb9eb3

test:
  secret_key_base: ee7c77cecbf0b957cfdb434b9ddc18702c1fb94cebd05499e4eb1fab0ddf97659baf4a50524c64be24a3ad8a25c3ae9e5a62b70e48637a6788b98ecc1e635931

# Do not keep production secrets in the repository,
# instead read values from the environment.
production:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
