# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rake secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

development:
  secret_key_base: 0d15ffd0fff05373bfb1ab597f00f7021927cc93e53fa5c50f8468b41e4207161e9027e1647b9a3d25ccde3af245299988c06d5fe4dfb10f97e77d3c4f6ea0fe

test:
  secret_key_base: 0a694e115080d31e68b33c7eed19d91b8c3d047305e4f868e5213c6ab40d922108f431144b5cb71c2d789aab85bd57d4954a924a82245920ab3b5df3a5f46f79

# Do not keep production secrets in the repository,
# instead read values from the environment.
production:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
