# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rake secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

development:
  secret_key_base: 0a3423bbce0cda5367dc77b0bd2d1c3edf7285510e7dc06a2db7639c235f4fa1b7323a38298b3d38df6ccf037ab4a0b4ead54c29ad826500e4883bf362675eed

test:
  secret_key_base: fd9ac8edf5df5abf858d40dadd6d43ef8638cb3aad41e99fa197be6a92e99ce002ec94564bf73d922643f079ee6a1015249231350e32f1e87f9b22df177a9c47

# Do not keep production secrets in the repository,
# instead read values from the environment.
production:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
